SELECT TOP 10 G.GENERE_ID, G.GENERE_NAME, COUNT(*) AS total_rentals
FROM RENTAL R
JOIN MOVIE M ON R.MOVIE_ID = M.MOVIE_ID
JOIN GENERE G ON M.GENERE_ID = G.GENERE_ID
GROUP BY G.GENERE_ID, G.GENERE_NAME
ORDER BY COUNT(*) DESC;

SELECT G.GENERE_ID, G.NAME
FROM GENERE G
WHERE G.GENERE_ID NOT IN (
    SELECT DISTINCT M.GENERE_ID
    FROM RENTAL R
    JOIN MOVIE M ON R.MOVIE_ID = M.MOVIE_ID
    WHERE R.RENTAL_DATE >= DATEADD(MONTH, -1, GETDATE())
);

SELECT 
    G.GENERE_NAME AS GENRE_NAME,
    M.MOVIE_NAME AS MOVIE_NAME,
    M.ADDED_DATE
FROM 
    MOVIE M
JOIN 
    GENERE G ON M.GENERE_ID = G.GENERE_ID
ORDER BY 
    G.GENERE_NAME, M.ADDED_DATE;
SELECT 
    U.USER_ID,
    U.ADMIN_ID,
    U.EMAIL,
    U.BUSSINESS_ADDRESS,
    U.PHONE,
    U.RESIDENCE_ADDRESS,
    U.BILLING_ADDRESS,
    U.CREDIT_CARD,
    COUNT(R.MOVIE_ID) AS TotalRentedMovies
FROM 
    "USER" U
LEFT JOIN 
    RENTAL R ON U.USER_ID = R.USER_ID
GROUP BY 
    U.USER_ID,
    U.ADMIN_ID,
    U.EMAIL,
    U.BUSSINESS_ADDRESS,
    U.PHONE,
    U.RESIDENCE_ADDRESS,
    U.BILLING_ADDRESS,
    U.CREDIT_CARD;

SELECT 
    G.GENERE_NAME,
    COUNT(*) AS TotalRentals,
    SUM(M.PRICE) AS TotalSales
FROM 
    RENTAL R
JOIN 
    MOVIE M ON R.MOVIE_ID = M.MOVIE_ID
JOIN 
    GENERE G ON M.GENERE_ID = G.GENERE_ID
GROUP BY 
    G.GENERE_NAME
ORDER BY 
    TotalRentals DESC;

	SELECT S.SUPPLIER_ID, S.SUPPLIER_NAME
FROM SUPPLIER S
WHERE NOT EXISTS (
    SELECT 1
    FROM MOVIE M
    WHERE M.SUPPLIER_ID = S.SUPPLIER_ID
      AND M.added_date >= DATEADD(MONTH, -3, GETDATE())
);

